IRIS_PX4_SITL:
  arm_srv: 'mavros/cmd/arming'
  set_mode_srv: 'mavros/set_mode'
  land_srv: 'mavros/cmd/land'
  param_set_srv: '/mavros/param/set'
  param_get_srv: '/mavros/param/get'

  state_topic: 'mavros/state'
  extended_state_topic: 'mavros/extended_state'
  pose_topic: 'mavros/local_position/pose'
  velocity_body_topic: 'mavros/local_position/velocity_body'
  global_position_topic: 'mavros/global_position/global'
  setpoint_raw_local: 'mavros/setpoint_raw/local'
  cam_frontal_topic: '/iris/cam_frontal/image_raw'
  cam_ventral_topic: '/iris/cam_ventral/image_raw'
TELLO_REAL:
  arm_srv: ''
  set_mode_srv: ''
  land_srv: ''
  param_set_srv: ''
  param_get_srv: ''

  state_topic: ''
  extended_state_topic: ''
  pose_topic: ''
  velocity_body_topic: ''
  global_position_topic: ''
  setpoint_raw_local: ''
  cam_frontal_topic: ''
  cam_ventral_topic: ''
